### PR TITLE
add eslint

### PR DESCRIPTION
**Pull request by i5dr0id**
This closes issue #6

### CODE REVIEW

**Comment by i5dr0id** [comment]
> _No description provided._

This closes #6

**Comment by GrosSacASac** [comment]
Thanks, please follow the instructions noted here https://github.com/GrosSacASac/JavaScript-Set-Up/tree/master/js/red-javascript-style-guide#lint-set-up

Extend the red config, this will be easier to maintain :
    extends": ["red"]

do not remove any line from the gitignore,

put the config inside package.json to have 1 less extra file

**Comment by GrosSacASac** [comment]
Why add babel-eslint ?

**Comment by i5dr0id** [comment]
> Why add babel-eslint ?

I have removed it

**Comment by GrosSacASac** [comment]
merged

**Pull request merged**
